### PR TITLE
Support builds for Windows

### PR DESCRIPTION
**Pull request by enochtsang**
Included instructions in the README to compile for Windows and OSX.
Edited Linux instructions to be a bit more bulletproof.
Added Visual Studio project files. They are set up using relative paths.
Getting the libraries is hosted externally, so this will break one day.
Ignored lib/ folder.
Add instructions to move asset folder for Windows builds.
Add directory structure of dependencies for Windows builds.

@kychum @Pigglesworth please try this on your windows machines at home.
@ammunoz please review.

### CODE REVIEW

**Comment by ammunoz** [comment]
My approval assumes that this works consistently on other machines

**Comment by kychum** [comment]
Forgot to mention that the branch works for me, using VS2017.

I'm assuming that any time we need to update the libs you'll need to repackage and upload the zip to your server, but don't see any other way around that at the moment.

**Comment by enochtsang** [comment]
Yup,  that's how that will work.

**Comment by enochtsang** [comment]
Someone needs to put an approved review before it can be merged. I don't like the idea of having someone libraries in the repo.

**Comment by enochtsang** [comment]
Duplicated work in new pr

**Pull request closed without merging**
